version: '3.4'
services:
  itco.ids.develop:
    image: '${DOCKER_REGISTRY-}itco-ids-develop'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: itco-ids-develop
    environment:
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 127.0.0.1:40001:80

networks:
  default:
    external:
      name: itco-develop
